### PR TITLE
Fix bugs with sret and memcpy

### LINKED ISSUE #137: Assigner fails to detect return pointer `sret` in circuit arguments
Minimal example:

```llvm
define void @test(ptr sret(__zkllvm_field_pallas_base) %0) #0 {
  ret void
}

attributes #0 = { circuit }
```

Input:

```json
[]
```

Result:

```
Public input does not match the circuit signature: not enough values in the input file.
```

Assigner fails to detect `sret` attribute in arguments. It returns size mismatch error first, before even looking at the attributes.

### PR DESCRIPTION
**Pull request by makxenov**
Closes #137

### CODE REVIEW

File: include/nil/blueprint/layout_resolver.hpp [hunk 1]
```diff
@@ -121,8 +111,8 @@ namespace nil {
                 case llvm::Type::ArrayTyID: {
                     auto *array_ty = llvm::cast<llvm::ArrayType>(type);
                     llvm::Type *elem_ty = array_ty->getElementType();
-                    std::vector<unsigned> elem_layout = get_type_layout<BlueprintFieldType>(elem_ty);
-                    std::vector<unsigned> res;
+                    auto elem_layout = get_type_layout<BlueprintFieldType>(elem_ty);
```
Comment (CblPOK-git) [inline include/nil/blueprint/layout_resolver.hpp:114]: it's better to declare type explicitly instead of using "auto"

File: include/nil/blueprint/layout_resolver.hpp [hunk 2]
```diff
@@ -131,8 +121,8 @@ namespace nil {
                 case llvm::Type::FixedVectorTyID: {
                     auto *vec_ty = llvm::cast<llvm::FixedVectorType>(type);
                     llvm::Type *elem_ty = vec_ty->getElementType();
-                    std::vector<unsigned> elem_layout = get_type_layout<BlueprintFieldType>(elem_ty);
-                    std::vector<unsigned> res;
+                    auto elem_layout = get_type_layout<BlueprintFieldType>(elem_ty);
```
Comment (CblPOK-git) [inline include/nil/blueprint/layout_resolver.hpp:124]: same

File: include/nil/blueprint/layout_resolver.hpp [hunk 3]
```diff
@@ -143,6 +133,16 @@ namespace nil {
                 }
             }
 
+            template<typename BlueprintFieldType>
+            size_t get_cells_num(llvm::Type *type) {
+                auto layout = get_type_layout<BlueprintFieldType>(type);
```
Comment (CblPOK-git) [inline include/nil/blueprint/layout_resolver.hpp:138]: and here

**Review by CblPOK-git — CHANGES_REQUESTED** [review]

File: include/nil/blueprint/input_reader.hpp [hunk 4]
```diff
@@ -372,6 +374,11 @@ namespace nil {
                 case llvm::Type::EllipticCurveTyID:
                 case llvm::Type::IntegerTyID:
                 case llvm::Type::FixedVectorTyID:{
+                    if (!value.is_object()) {
+                        std::ostringstream error;
+                        error << "Unexpected JSON element: expected object, got " << value;
```
Comment (nkaskov) [inline include/nil/blueprint/input_reader.hpp:379]: Can we use error level ERROR for that instead? It seems to me that the user will expect this kind of stuff to appear when boost::log::trivial::error is chosen.

Comment (makxenov) [reply include/nil/blueprint/input_reader.hpp:379]: For now, it is necessary to crash with `UNREACHABLE` here, because we don't have a correct error handler in the input reader. But all these assertions should be replaced with error logs, here's an issue on it: https://github.com/NilFoundation/zkLLVM/issues/358
